services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm start
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    env_file:
      - .env
    ports:
      - "5173:5173"
    environment:
      - API_URL=http://<BACKEND_SERVER_IP>:3000/api
      - ALLOWED_ORIGINS=http://localhost:5173
    depends_on:
      - backend
    networks:
      - app-network
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:5173/health || exit 1"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    restart: unless-stopped


networks:
  app-network:
