services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerfileDev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./backend:/app:delegated
      - /app/node_modules
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run dev
      "
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerfileDev
      args:
        VITE_API_URL: ${VITE_API_URL}
    env_file:
      - .env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${VITE_API_URL}
      - ALLOWED_ORIGINS=http://localhost:5173
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
