services:
  backend:
    build: 
      context: ./backend
      dockerfile: DockerfileDev
      target: dev
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app:delegated
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: 
      context: ./frontend
      dockerfile: DockerfileDev
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:3000
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    networks:
      - app-network
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:5173/health || exit 1"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

networks:
  app-network:
